# Generated by Django 4.2.4 on 2023-08-23 15:17

import apps.documents.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='path',
            field=models.FileField(default=1, upload_to='documents/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'text']), apps.documents.utils.validate_file_size]),
            preserve_default=False,
        ),
    ]
